// Embedded HTML/JS for the web dashboard. Served verbatim from
// HTTPServer when the user hits ``GET /``. No build step, no
// asset pipeline — just a single string constant. Vanilla JS,
// no frameworks. Polls /api/status every 2s, renders to the page.
//
// Auth flow:
//   - First visit: token comes from ``?token=...`` query string,
//     gets stored in localStorage so the user doesn't need to
//     paste it again.
//   - Subsequent visits: token read from localStorage and added
//     to fetch() requests as ``Authorization: Bearer ...``.
//   - If neither source has a token, the page shows a paste box.
//
// The token comes from either the user's config (``[web].auth_token``)
// or — if unset — a random token generated by DaemonScaffold and
// written to ``$STATE_DIR/web-token`` on startup.

enum WebDashboard {
    static let html = ##"""
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>rmsync</title>
<style>
  :root {
    --fg: #1a1a1a;
    --muted: #555;
    --bg: #fafafa;
    --card: #fff;
    --border: #ddd;
    --accent: #2563eb;
    --good: #16a34a;
    --warn: #d97706;
    --bad: #dc2626;
    --mono: ui-monospace, "SF Mono", Menlo, Consolas, monospace;
  }
  @media (prefers-color-scheme: dark) {
    :root {
      --fg: #f5f5f5; --muted: #aaa; --bg: #111; --card: #1c1c1c;
      --border: #333; --accent: #60a5fa;
    }
  }
  * { box-sizing: border-box; }
  body {
    font: 14px/1.5 system-ui, -apple-system, "Segoe UI", sans-serif;
    color: var(--fg); background: var(--bg);
    margin: 0; padding: 20px;
    max-width: 860px; margin-left: auto; margin-right: auto;
  }
  h1 { margin: 0 0 16px; font-size: 22px; }
  h2 { margin: 24px 0 10px; font-size: 15px; color: var(--muted); }
  .grid {
    display: grid; gap: 12px;
    grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
  }
  .card {
    background: var(--card); border: 1px solid var(--border);
    border-radius: 8px; padding: 12px 14px;
  }
  .card h3 { margin: 0 0 4px; font-size: 11px;
             text-transform: uppercase; color: var(--muted);
             letter-spacing: 0.04em; }
  .card .v  { font-size: 20px; font-weight: 600; }
  .card .sub { font-size: 12px; color: var(--muted); }
  .badge {
    display: inline-block; padding: 1px 8px; border-radius: 999px;
    font-size: 11px; font-weight: 600; text-transform: uppercase;
    letter-spacing: 0.04em;
  }
  .ok    { background: rgba(22, 163, 74, .15); color: var(--good); }
  .warn  { background: rgba(217, 119, 6, .15); color: var(--warn); }
  .bad   { background: rgba(220, 38, 38, .15); color: var(--bad); }
  table { width: 100%; border-collapse: collapse; font-size: 13px; }
  th, td { text-align: left; padding: 6px 8px; border-bottom: 1px solid var(--border); }
  th { color: var(--muted); font-weight: 500; font-size: 11px;
       text-transform: uppercase; letter-spacing: 0.04em; }
  td.path { font-family: var(--mono); font-size: 12px; }
  .actions { display: flex; gap: 8px; margin: 12px 0; flex-wrap: wrap; }
  button {
    background: var(--card); color: var(--fg);
    border: 1px solid var(--border); border-radius: 6px;
    padding: 8px 12px; font: inherit; cursor: pointer;
  }
  button:hover { border-color: var(--accent); color: var(--accent); }
  button:disabled { opacity: 0.5; cursor: not-allowed; }
  .auth-prompt {
    margin: 40px auto; max-width: 480px;
    padding: 24px; background: var(--card);
    border: 1px solid var(--border); border-radius: 8px;
  }
  .auth-prompt input {
    width: 100%; font: inherit; padding: 8px;
    border: 1px solid var(--border); border-radius: 6px;
    background: var(--bg); color: var(--fg);
    margin-bottom: 12px;
  }
  .meta { color: var(--muted); font-size: 12px; }
  code { font-family: var(--mono); background: rgba(0,0,0,.04); padding: 1px 4px; border-radius: 3px; }
  .footer { margin-top: 32px; color: var(--muted); font-size: 11px; }
</style>
</head>
<body>

<div id="app"></div>

<script>
(function () {
  // Pull token from ?token=... query, or fall back to localStorage.
  const url = new URL(location.href);
  let token = url.searchParams.get("token");
  if (token) {
    localStorage.setItem("rmsync_token", token);
    // Strip the query so the URL bar isn't carrying the token around.
    url.searchParams.delete("token");
    history.replaceState(null, "", url.pathname + (url.search ? "?" + url.searchParams : ""));
  } else {
    token = localStorage.getItem("rmsync_token") || "";
  }

  const app = document.getElementById("app");

  if (!token) {
    app.innerHTML = `
      <h1>rmsync</h1>
      <div class="auth-prompt">
        <p>Paste your dashboard token to continue. The daemon writes it to
        <code>$STATE_DIR/web-token</code> on first start; on Docker that's
        <code>./data/state/web-token</code>.</p>
        <input id="tokenInput" type="text" placeholder="rmsync-..." autofocus>
        <button id="tokenSave">save</button>
      </div>`;
    document.getElementById("tokenSave").onclick = () => {
      const v = document.getElementById("tokenInput").value.trim();
      if (v) { localStorage.setItem("rmsync_token", v); location.reload(); }
    };
    return;
  }

  function fmtDate(s) {
    if (!s) return "—";
    try {
      const d = new Date(s);
      const now = new Date();
      const diffSec = Math.floor((now - d) / 1000);
      if (diffSec < 0) return d.toLocaleString();
      if (diffSec < 60)   return diffSec + "s ago";
      if (diffSec < 3600) return Math.floor(diffSec / 60) + "m ago";
      if (diffSec < 86400) return Math.floor(diffSec / 3600) + "h ago";
      return Math.floor(diffSec / 86400) + "d ago";
    } catch (e) { return s; }
  }

  function fmtPath(p) {
    if (!p) return "—";
    return p.length > 50 ? "…" + p.slice(-47) : p;
  }

  function badge(state) {
    if (state === "idle") return `<span class="badge ok">idle</span>`;
    if (state === "syncing") return `<span class="badge warn">syncing</span>`;
    if (state === "paused") return `<span class="badge warn">paused</span>`;
    return `<span class="badge bad">${state}</span>`;
  }

  async function req(method, path, body) {
    const r = await fetch(path, {
      method,
      headers: {
        "Authorization": "Bearer " + token,
        "Content-Type": "application/json",
      },
      body: body ? JSON.stringify(body) : null,
    });
    if (r.status === 401) {
      localStorage.removeItem("rmsync_token");
      location.reload();
      return null;
    }
    return r.ok ? await r.json().catch(() => ({})) : null;
  }

  function render(s) {
    if (!s) {
      app.innerHTML = `<h1>rmsync</h1><p class="meta">daemon unreachable</p>`;
      return;
    }
    const recent = (s.recent_docs || []).map(d => `
      <tr>
        <td class="path">${fmtPath(d.local_path)}</td>
        <td>${fmtDate(d.last_pull_at)}</td>
        <td>${fmtDate(d.last_push_at)}</td>
        <td>${d.conflict ? '<span class="badge bad">conflict</span>' :
              d.error ? '<span class="badge bad">' + d.error + '</span>' :
              '<span class="badge ok">ok</span>'}</td>
      </tr>`).join("");

    const conflicts = (s.conflict_docs || []).map(d => `
      <tr><td class="path">${fmtPath(d.local_path)}</td><td>${d.doc_id}</td></tr>
    `).join("");

    app.innerHTML = `
      <h1>rmsync ${badge(s.state)}</h1>
      <div class="grid">
        <div class="card"><h3>tracked docs</h3><div class="v">${s.tracked_docs}</div></div>
        <div class="card"><h3>queue depth</h3><div class="v">${s.queue_depth}</div></div>
        <div class="card"><h3>conflicts</h3><div class="v">${s.conflicts}</div></div>
        <div class="card"><h3>parked errors</h3><div class="v">${s.errors}</div></div>
        <div class="card">
          <h3>last pull</h3>
          <div class="v" style="font-size:14px">${fmtDate(s.last_pull_at)}</div>
        </div>
        <div class="card">
          <h3>last push</h3>
          <div class="v" style="font-size:14px">${fmtDate(s.last_push_at)}</div>
        </div>
      </div>

      <div class="actions">
        <button onclick="window.rmAction('sync-now')">sync now</button>
        <button onclick="window.rmAction(${s.paused ? "'resume'" : "'pause'"})">
          ${s.paused ? "resume" : "pause"}
        </button>
      </div>

      <h2>recent docs</h2>
      <table>
        <thead><tr><th>local path</th><th>last pull</th><th>last push</th><th>state</th></tr></thead>
        <tbody>${recent || `<tr><td colspan="4" class="meta">no tracked docs yet</td></tr>`}</tbody>
      </table>

      ${conflicts ? `
        <h2>unresolved conflicts</h2>
        <table>
          <thead><tr><th>local path</th><th>doc id</th></tr></thead>
          <tbody>${conflicts}</tbody>
        </table>` : ""}

      <p class="footer">
        rmsync ${s.version || "?"} · pid ${s.pid} ·
        sync_dir <code>${s.sync_dir}</code> · remote <code>${s.remote_folder}</code> ·
        updated ${fmtDate(s.updated_at)}
      </p>`;
  }

  window.rmAction = async function (name) {
    await req("POST", "/api/" + name);
    poll();
  };

  async function poll() {
    const s = await req("GET", "/api/status");
    render(s);
  }

  poll();
  setInterval(poll, 2000);
})();
</script>
</body>
</html>
"""##
}
