# Homebrew formula for rmsync.
#
# This file lives in the main repo for reference and testing
# (`brew install --build-from-source ./Formula/rmsync.rb` from inside
# a clone). For the public tap, copy this file into the tap repo —
# see docs/HOMEBREW.md for the full setup.
#
# Bumping versions:
#   1. Push a new `vX.Y.Z` tag on this repo.
#   2. Update `url` below to point at the new tag's source tarball.
#   3. Run `brew fetch --build-from-source rmsync` and copy the SHA
#      reported after "Already downloaded" into `sha256`.
#   4. Commit to the tap repo.
#
# Or, if you set up the GitHub Actions workflow in
# `.github/workflows/release.yml`, step 2–3 are done for you on tag push.

class Rmsync < Formula
  desc "Bidirectional macOS ↔ reMarkable tablet Markdown sync daemon"
  homepage "https://github.com/madhavsuresh/rmsync"
  url "https://github.com/madhavsuresh/rmsync/archive/refs/tags/v0.2.0.tar.gz"
  sha256 "0000000000000000000000000000000000000000000000000000000000000000"
  license "MIT"
  head "https://github.com/madhavsuresh/rmsync.git", branch: "main"

  # Brew audit expects a specific dep order: build-time deps first,
  # then runtime formula deps, then OS constraints.

  # Swift 6+ lives in Xcode 16. Command-line tools work too but brew
  # can't enforce that distinction.
  depends_on xcode: ["16.0", :build]

  # rmapi is required at runtime; we shell out to it for all cloud access.
  # io41/tap maintains a recent formula for the Go binary.
  depends_on "io41/tap/rmapi"

  depends_on macos: :ventura

  def install
    cd "swift" do
      system "swift", "build",
             "--disable-sandbox",
             "-c", "release",
             "--arch", "arm64",
             "--arch", "x86_64"

      # Universal-binary output lives under .build/apple for multi-arch
      # builds; SPM switches layouts silently based on --arch flags.
      release = if Dir[".build/apple/Products/Release/*"].any?
        ".build/apple/Products/Release"
      else
        ".build/release"
      end

      bin.install "#{release}/rmsync"
      bin.install "#{release}/rmsync-menubar"
    end

    # Ship plist templates, assets, and docs so the post-install helper
    # can render real plists into ~/Library/LaunchAgents.
    pkgshare.install "scripts"
    pkgshare.install "assets"
    doc.install Dir["docs/*.md"]
    doc.install "README.md"

    # Render a tiny helper that installs the two launchd agents. We
    # generate it here so it has the right opt_bin path baked in.
    (bin/"rmsync-install-agents").write agent_installer_script
    chmod 0755, bin/"rmsync-install-agents"

    # Paired uninstaller — matches what uninstall.sh does, minus the
    # source-tree cleanup that doesn't apply to brew installs.
    (bin/"rmsync-uninstall-agents").write agent_uninstaller_script
    chmod 0755, bin/"rmsync-uninstall-agents"
  end

  def caveats
    <<~EOS
      rmsync ships a sync daemon and a separate menu bar app. Neither
      is started by `brew install` — you finish setup in three steps:

        1. Authenticate rmapi (one-time per Mac):
             rmapi
           Paste the 8-char code from
             https://my.remarkable.com/device/desktop/connect

        2. Install and boot both launchd agents:
             rmsync-install-agents

        3. Verify:
             rmsync doctor
             rmsync status

      The default sync dir is ~/rmsync-writing. Move it anywhere
      (iCloud, Dropbox, a git repo) with:
          rmsync relocate ~/path/to/new/dir

      To tear down later — ORDER MATTERS:
          rmsync-uninstall-agents    # first, while the helper still exists
          brew uninstall rmsync      # then this
      If you reverse the order, launchd will keep trying to relaunch a
      deleted binary. Recover by removing the plists manually from
      ~/Library/LaunchAgents/.

      Full operational guide:
          #{doc}/USAGE.md

      Single-file context for LLM help:
          #{doc}/LLM_CONTEXT.md
    EOS
  end

  test do
    # `--help` exits 0 on argument-parser-based CLIs and prints a
    # subcommand list. Enough to prove the binary loads its dynamic
    # libraries cleanly.
    help = shell_output("#{bin}/rmsync --help")
    assert_match "status", help
    assert_match "doctor", help
    assert_match "relocate", help

    # Menu bar is a GUI binary — running it would open a NSStatusItem
    # in a sandboxed brew test shell. Just check the file is executable.
    assert_predicate bin/"rmsync-menubar", :executable?
  end

  private

  # --- helpers --------------------------------------------------------

  # Renders a shell script that generates both plists with correct
  # paths and bootstraps them via launchctl. Idempotent; safe to re-run.
  def agent_installer_script
    <<~SH
      #!/bin/sh
      # Generated by the rmsync Homebrew formula. Writes both launchd
      # agent plists into ~/Library/LaunchAgents and bootstraps them.
      set -eu

      DAEMON_BIN="#{opt_bin}/rmsync"
      MENUBAR_BIN="#{opt_bin}/rmsync-menubar"
      TEMPLATES="#{pkgshare}/scripts"
      LA="$HOME/Library/LaunchAgents"
      UID_NUM=$(id -u)

      mkdir -p "$LA" \\
               "$HOME/Library/Logs/rmsync" \\
               "$HOME/Library/Application Support/rmsync" \\
               "$HOME/.config/rmsync"

      render() {
        # $1 template, $2 destination, $3 binary path
        sed -e "s|__HOME__|$HOME|g" \\
            -e "s|__RMSYNC_BIN__|$3|g" \\
            -e "s|__MENUBAR_BIN__|$3|g" \\
            "$1" > "$2"
      }

      render "$TEMPLATES/com.user.rmsync.swift.plist.template" \\
             "$LA/com.user.rmsync.plist" "$DAEMON_BIN"
      render "$TEMPLATES/com.user.rmsync.menubar.plist.template" \\
             "$LA/com.user.rmsync.menubar.plist" "$MENUBAR_BIN"

      # bootout-then-bootstrap, with a tiny retry loop to dodge the
      # launchd teardown race.
      boot() {
        label=$1
        launchctl bootout "gui/$UID_NUM/$label" 2>/dev/null || true
        n=0
        while ! launchctl bootstrap "gui/$UID_NUM" "$LA/$label.plist" 2>/dev/null; do
          n=$((n + 1))
          if [ $n -ge 20 ]; then
            echo "failed to bootstrap $label after $n attempts" >&2
            return 1
          fi
          sleep 0.25
        done
      }
      boot com.user.rmsync
      boot com.user.rmsync.menubar

      echo "rmsync agents installed and started."
      echo "Next: rmsync doctor"
    SH
  end

  def agent_uninstaller_script
    <<~SH
      #!/bin/sh
      # Stops both agents and removes their plists. Leaves your state,
      # config, logs, and synced files untouched.
      set -eu

      LA="$HOME/Library/LaunchAgents"
      UID_NUM=$(id -u)

      for label in com.user.rmsync com.user.rmsync.menubar; do
        launchctl bootout "gui/$UID_NUM/$label" 2>/dev/null || true
        rm -f "$LA/$label.plist"
      done

      echo "rmsync agents removed."
      echo "State/config/logs are still at:"
      echo "  ~/.config/rmsync/"
      echo "  ~/Library/Application Support/rmsync/"
      echo "  ~/Library/Logs/rmsync/"
      echo "Delete those manually if you want a full wipe."
    SH
  end
end
