#!/bin/sh
# rmsync Docker quickstart. Usage:
#
#   curl -fsSL https://raw.githubusercontent.com/madhavsuresh/rmsync/main/scripts/docker-quickstart.sh | sh
#
# or, with a custom directory:
#
#   curl -fsSL https://raw.githubusercontent.com/madhavsuresh/rmsync/main/scripts/docker-quickstart.sh \
#       | sh -s -- /opt/rmsync
#
# What this does:
#
#   1. Verifies docker + docker compose are installed.
#   2. Creates ./rmsync (or the path you pass) with subdirs config/, state/, sync/.
#   3. Drops in a docker-compose.yml whose volumes bind to those subdirs.
#   4. Pulls the latest amd64 image from ghcr.io and starts the daemon.
#   5. Prints the exact auth, init, and verify commands to run next.
#
# Idempotent: safe to re-run. If the directory already exists with a
# config, the script preserves it and just brings the container up.
set -eu

TARGET="${1:-$PWD/rmsync}"
IMAGE="ghcr.io/madhavsuresh/rmsync:latest"

# ── output helpers ───────────────────────────────────────────────────
green() { printf '\033[32m%s\033[0m\n' "$*"; }
yellow(){ printf '\033[33m%s\033[0m\n' "$*"; }
red()   { printf '\033[31m%s\033[0m\n' "$*" >&2; }
bold()  { printf '\033[1m%s\033[0m\n' "$*"; }
step()  { bold ""; bold "▸ $*"; }

# ── pre-flight ───────────────────────────────────────────────────────
step "Checking prerequisites"
if ! command -v docker >/dev/null 2>&1; then
    red "docker not found. Install Docker Engine + the compose plugin first:"
    red "  https://docs.docker.com/engine/install/"
    exit 1
fi
if ! docker compose version >/dev/null 2>&1; then
    red "docker compose plugin not available. On Debian/Ubuntu:"
    red "  sudo apt-get install docker-compose-plugin"
    exit 1
fi
if ! docker info >/dev/null 2>&1; then
    red "docker daemon isn't reachable. Start it (or fix your permissions):"
    red "  sudo systemctl start docker        # systemd hosts"
    red "  sudo usermod -aG docker \$USER     # then re-login to use docker without sudo"
    exit 1
fi
green "  docker + compose ready"

# ── directory layout ─────────────────────────────────────────────────
step "Provisioning $TARGET"
mkdir -p "$TARGET"/data/config "$TARGET"/data/state "$TARGET"/data/sync
green "  data/{config,state,sync} created"

# ── docker-compose.yml ───────────────────────────────────────────────
COMPOSE_PATH="$TARGET/docker-compose.yml"
if [ -f "$COMPOSE_PATH" ]; then
    yellow "  $COMPOSE_PATH already exists; leaving it alone"
else
    # Inline the compose template so this script is self-contained
    # (one curl|bash, no second download). Mirrors the file at
    # docker-compose.yml in the source repo, with the user's
    # current uid/gid baked in so files written into ./data/sync
    # are owned by the invoking user, not root.
    UID_GID="$(id -u):$(id -g)"
    cat > "$COMPOSE_PATH" <<EOF
# Generated by docker-quickstart.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# Edit freely. See docs/DOCKER.md for the full reference.

services:
  rmsync:
    image: $IMAGE
    container_name: rmsync
    restart: unless-stopped
    user: "$UID_GID"
    volumes:
      - ./data/config:/config
      - ./data/state:/state
      - ./data/sync:/sync
    healthcheck:
      test: ["CMD", "/usr/local/bin/rmsync", "status"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 60s
EOF
    green "  $COMPOSE_PATH (UID:GID set to $UID_GID for clean file ownership)"
fi

# ── pull + up ────────────────────────────────────────────────────────
step "Pulling image"
(cd "$TARGET" && docker compose pull)
step "Starting container"
(cd "$TARGET" && docker compose up -d)
green "  container 'rmsync' is up"

# ── next steps ───────────────────────────────────────────────────────
bold ""
bold "═══════════════════════════════════════════════════════════════"
bold "  rmsync is running. Three more steps:"
bold "═══════════════════════════════════════════════════════════════"
bold ""
bold "  1) Authenticate rmapi (one-time, interactive):"
echo "       cd $TARGET"
echo "       docker exec -it rmsync rmapi"
echo ""
echo "     The prompt will ask for an 8-character pairing code."
echo "     Get one at: https://my.remarkable.com/device/desktop/connect"
echo ""
bold "  2) Initialize the configured cloud folder:"
echo "       docker exec rmsync rmsync init"
echo ""
bold "  3) Verify everything works:"
echo "       docker exec rmsync rmsync doctor"
echo "       docker logs -f rmsync"
bold ""
echo "Default sync directory: $TARGET/data/sync"
echo "Edit a .md there, then push it explicitly:"
echo "  docker exec rmsync rmsync push <path>"
echo ""
echo "Full guide: https://github.com/madhavsuresh/rmsync/blob/main/docs/DOCKER.md"
